/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.api;

import org.lamemind.esprinetclient.invoker.ApiException;
import org.lamemind.esprinetclient.model.CashAndCarriesProductAvailabilityByCodeOutput;
import org.lamemind.esprinetclient.model.CashAndCarriesProductPricingByCodeOutput;
import org.lamemind.esprinetclient.model.CashAndCarryProductAvailabilityByCodeOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CashandcarriesApi
 */
@Ignore
public class CashandcarriesApiTest {

    private final CashandcarriesApi api = new CashandcarriesApi();

    
    /**
     * Get a Product Availability Info by the Esprinet or Customer product code for all the Cash And Carries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAndCarryAvailabilityGetTest() throws ApiException {
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        CashAndCarriesProductAvailabilityByCodeOutput response = api.cashAndCarryAvailabilityGet(esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Get a Product Availability Info by the Esprinet or Customer product code for  the chosen Cash And Carry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAndCarryAvailabilityGetByCashTest() throws ApiException {
        String cashId = null;
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        CashAndCarryProductAvailabilityByCodeOutput response = api.cashAndCarryAvailabilityGetByCash(cashId, esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Get a Product Pricing Info by the Esprinet or Customer product code for all the Cash And Carries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAndCarryPricingGetTest() throws ApiException {
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        CashAndCarriesProductPricingByCodeOutput response = api.cashAndCarryPricingGet(esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Get a Product Pricing Info by the Esprinet or Customer product code for  the chosen Cash And Carry
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cashAndCarryPricingGetByCashTest() throws ApiException {
        String cashId = null;
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        CashAndCarriesProductPricingByCodeOutput response = api.cashAndCarryPricingGetByCash(cashId, esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
}
