/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.api;

import org.lamemind.esprinetclient.invoker.ApiException;
import org.lamemind.esprinetclient.model.QuotationInputResponse;
import org.lamemind.esprinetclient.model.QuotationOutput;
import org.lamemind.esprinetclient.model.QuotationsInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerQuotationsApi
 */
@Ignore
public class CustomerQuotationsApiTest {

    private final CustomerQuotationsApi api = new CustomerQuotationsApi();

    
    /**
     * Gets the quotation previously inserted by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quotationGetTest() throws ApiException {
        Integer id = null;
        String xConsumerTransactionId = null;
        QuotationOutput response = api.quotationGet(id, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Creates a new quotation request containing the specified list of products into the Esprinet systems.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void quotationPostTest() throws ApiException {
        QuotationsInput quotation = null;
        String xConsumerTransactionId = null;
        QuotationInputResponse response = api.quotationPost(quotation, xConsumerTransactionId);

        // TODO: test validations
    }
    
}
