/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.api;

import org.lamemind.esprinetclient.invoker.ApiException;
import org.lamemind.esprinetclient.model.LoginInput;
import org.lamemind.esprinetclient.model.LoginOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LoginApi
 */
@Ignore
public class LoginApiTest {

    private final LoginApi api = new LoginApi();

    
    /**
     * Performs the logon to the service.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginPostTest() throws ApiException {
        LoginInput loginInput = null;
        String xConsumerTransactionId = null;
        LoginOutput response = api.loginPost(loginInput, xConsumerTransactionId);

        // TODO: test validations
    }
    
}
