/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * CustomerDepotDeliveryNoteLineDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class CustomerDepotDeliveryNoteLineDto {
  @SerializedName("esprinetLineNumber")
  private Integer esprinetLineNumber = null;

  @SerializedName("esprinetProductCode")
  private String esprinetProductCode = null;

  @SerializedName("customerProductCode")
  private String customerProductCode = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("serialNumbers")
  private List<String> serialNumbers = null;

  public CustomerDepotDeliveryNoteLineDto esprinetLineNumber(Integer esprinetLineNumber) {
    this.esprinetLineNumber = esprinetLineNumber;
    return this;
  }

   /**
   * Get esprinetLineNumber
   * @return esprinetLineNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEsprinetLineNumber() {
    return esprinetLineNumber;
  }

  public void setEsprinetLineNumber(Integer esprinetLineNumber) {
    this.esprinetLineNumber = esprinetLineNumber;
  }

  public CustomerDepotDeliveryNoteLineDto esprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
    return this;
  }

   /**
   * Esprinet product code.
   * @return esprinetProductCode
  **/
  @ApiModelProperty(value = "Esprinet product code.")
  public String getEsprinetProductCode() {
    return esprinetProductCode;
  }

  public void setEsprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
  }

  public CustomerDepotDeliveryNoteLineDto customerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
    return this;
  }

   /**
   * Customer product code (if available).
   * @return customerProductCode
  **/
  @ApiModelProperty(value = "Customer product code (if available).")
  public String getCustomerProductCode() {
    return customerProductCode;
  }

  public void setCustomerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
  }

  public CustomerDepotDeliveryNoteLineDto quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Amount of ordered items.
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "Amount of ordered items.")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CustomerDepotDeliveryNoteLineDto serialNumbers(List<String> serialNumbers) {
    this.serialNumbers = serialNumbers;
    return this;
  }

  public CustomerDepotDeliveryNoteLineDto addSerialNumbersItem(String serialNumbersItem) {
    if (this.serialNumbers == null) {
      this.serialNumbers = new ArrayList<String>();
    }
    this.serialNumbers.add(serialNumbersItem);
    return this;
  }

   /**
   * Get serialNumbers
   * @return serialNumbers
  **/
  @ApiModelProperty(value = "")
  public List<String> getSerialNumbers() {
    return serialNumbers;
  }

  public void setSerialNumbers(List<String> serialNumbers) {
    this.serialNumbers = serialNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDepotDeliveryNoteLineDto customerDepotDeliveryNoteLineDto = (CustomerDepotDeliveryNoteLineDto) o;
    return Objects.equals(this.esprinetLineNumber, customerDepotDeliveryNoteLineDto.esprinetLineNumber) &&
        Objects.equals(this.esprinetProductCode, customerDepotDeliveryNoteLineDto.esprinetProductCode) &&
        Objects.equals(this.customerProductCode, customerDepotDeliveryNoteLineDto.customerProductCode) &&
        Objects.equals(this.quantity, customerDepotDeliveryNoteLineDto.quantity) &&
        Objects.equals(this.serialNumbers, customerDepotDeliveryNoteLineDto.serialNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(esprinetLineNumber, esprinetProductCode, customerProductCode, quantity, serialNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDepotDeliveryNoteLineDto {\n");
    
    sb.append("    esprinetLineNumber: ").append(toIndentedString(esprinetLineNumber)).append("\n");
    sb.append("    esprinetProductCode: ").append(toIndentedString(esprinetProductCode)).append("\n");
    sb.append("    customerProductCode: ").append(toIndentedString(customerProductCode)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    serialNumbers: ").append(toIndentedString(serialNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

