/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.Address;
import org.lamemind.esprinetclient.model.CustomerDepotOrderLineInputDto;

/**
 * CustomerDepotOrderInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class CustomerDepotOrderInput {
  @SerializedName("customerOrderId")
  private String customerOrderId = null;

  @SerializedName("orderLines")
  private List<CustomerDepotOrderLineInputDto> orderLines = new ArrayList<CustomerDepotOrderLineInputDto>();

  @SerializedName("deliverTo")
  private Address deliverTo = null;

  @SerializedName("invoiceTo")
  private Address invoiceTo = null;

  @SerializedName("cup")
  private String cup = null;

  @SerializedName("cig")
  private String cig = null;

  @SerializedName("invoiceComments")
  private String invoiceComments = null;

  @SerializedName("deliveryNoteComments")
  private String deliveryNoteComments = null;

  @SerializedName("shipmentPurpose")
  private String shipmentPurpose = null;

  @SerializedName("extraEmailAddresses")
  private List<String> extraEmailAddresses = null;

  public CustomerDepotOrderInput customerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
    return this;
  }

   /**
   * Customer-generated order id.
   * @return customerOrderId
  **/
  @ApiModelProperty(value = "Customer-generated order id.")
  public String getCustomerOrderId() {
    return customerOrderId;
  }

  public void setCustomerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
  }

  public CustomerDepotOrderInput orderLines(List<CustomerDepotOrderLineInputDto> orderLines) {
    this.orderLines = orderLines;
    return this;
  }

  public CustomerDepotOrderInput addOrderLinesItem(CustomerDepotOrderLineInputDto orderLinesItem) {
    this.orderLines.add(orderLinesItem);
    return this;
  }

   /**
   * Collection of lines (details) of the order.
   * @return orderLines
  **/
  @ApiModelProperty(required = true, value = "Collection of lines (details) of the order.")
  public List<CustomerDepotOrderLineInputDto> getOrderLines() {
    return orderLines;
  }

  public void setOrderLines(List<CustomerDepotOrderLineInputDto> orderLines) {
    this.orderLines = orderLines;
  }

  public CustomerDepotOrderInput deliverTo(Address deliverTo) {
    this.deliverTo = deliverTo;
    return this;
  }

   /**
   * The address where the order items should be delivered to.
   * @return deliverTo
  **/
  @ApiModelProperty(required = true, value = "The address where the order items should be delivered to.")
  public Address getDeliverTo() {
    return deliverTo;
  }

  public void setDeliverTo(Address deliverTo) {
    this.deliverTo = deliverTo;
  }

  public CustomerDepotOrderInput invoiceTo(Address invoiceTo) {
    this.invoiceTo = invoiceTo;
    return this;
  }

   /**
   * The billing Address.
   * @return invoiceTo
  **/
  @ApiModelProperty(value = "The billing Address.")
  public Address getInvoiceTo() {
    return invoiceTo;
  }

  public void setInvoiceTo(Address invoiceTo) {
    this.invoiceTo = invoiceTo;
  }

  public CustomerDepotOrderInput cup(String cup) {
    this.cup = cup;
    return this;
  }

   /**
   * The Cup field.
   * @return cup
  **/
  @ApiModelProperty(value = "The Cup field.")
  public String getCup() {
    return cup;
  }

  public void setCup(String cup) {
    this.cup = cup;
  }

  public CustomerDepotOrderInput cig(String cig) {
    this.cig = cig;
    return this;
  }

   /**
   * The Cig field.
   * @return cig
  **/
  @ApiModelProperty(value = "The Cig field.")
  public String getCig() {
    return cig;
  }

  public void setCig(String cig) {
    this.cig = cig;
  }

  public CustomerDepotOrderInput invoiceComments(String invoiceComments) {
    this.invoiceComments = invoiceComments;
    return this;
  }

   /**
   * The InvoiceComments field.
   * @return invoiceComments
  **/
  @ApiModelProperty(value = "The InvoiceComments field.")
  public String getInvoiceComments() {
    return invoiceComments;
  }

  public void setInvoiceComments(String invoiceComments) {
    this.invoiceComments = invoiceComments;
  }

  public CustomerDepotOrderInput deliveryNoteComments(String deliveryNoteComments) {
    this.deliveryNoteComments = deliveryNoteComments;
    return this;
  }

   /**
   * The DeliveryNoteComments field.
   * @return deliveryNoteComments
  **/
  @ApiModelProperty(value = "The DeliveryNoteComments field.")
  public String getDeliveryNoteComments() {
    return deliveryNoteComments;
  }

  public void setDeliveryNoteComments(String deliveryNoteComments) {
    this.deliveryNoteComments = deliveryNoteComments;
  }

  public CustomerDepotOrderInput shipmentPurpose(String shipmentPurpose) {
    this.shipmentPurpose = shipmentPurpose;
    return this;
  }

   /**
   * The ShipmentPurpose field.
   * @return shipmentPurpose
  **/
  @ApiModelProperty(required = true, value = "The ShipmentPurpose field.")
  public String getShipmentPurpose() {
    return shipmentPurpose;
  }

  public void setShipmentPurpose(String shipmentPurpose) {
    this.shipmentPurpose = shipmentPurpose;
  }

  public CustomerDepotOrderInput extraEmailAddresses(List<String> extraEmailAddresses) {
    this.extraEmailAddresses = extraEmailAddresses;
    return this;
  }

  public CustomerDepotOrderInput addExtraEmailAddressesItem(String extraEmailAddressesItem) {
    if (this.extraEmailAddresses == null) {
      this.extraEmailAddresses = new ArrayList<String>();
    }
    this.extraEmailAddresses.add(extraEmailAddressesItem);
    return this;
  }

   /**
   * Extra email addresses to send emails to inform the insertion of the new order
   * @return extraEmailAddresses
  **/
  @ApiModelProperty(value = "Extra email addresses to send emails to inform the insertion of the new order")
  public List<String> getExtraEmailAddresses() {
    return extraEmailAddresses;
  }

  public void setExtraEmailAddresses(List<String> extraEmailAddresses) {
    this.extraEmailAddresses = extraEmailAddresses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDepotOrderInput customerDepotOrderInput = (CustomerDepotOrderInput) o;
    return Objects.equals(this.customerOrderId, customerDepotOrderInput.customerOrderId) &&
        Objects.equals(this.orderLines, customerDepotOrderInput.orderLines) &&
        Objects.equals(this.deliverTo, customerDepotOrderInput.deliverTo) &&
        Objects.equals(this.invoiceTo, customerDepotOrderInput.invoiceTo) &&
        Objects.equals(this.cup, customerDepotOrderInput.cup) &&
        Objects.equals(this.cig, customerDepotOrderInput.cig) &&
        Objects.equals(this.invoiceComments, customerDepotOrderInput.invoiceComments) &&
        Objects.equals(this.deliveryNoteComments, customerDepotOrderInput.deliveryNoteComments) &&
        Objects.equals(this.shipmentPurpose, customerDepotOrderInput.shipmentPurpose) &&
        Objects.equals(this.extraEmailAddresses, customerDepotOrderInput.extraEmailAddresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOrderId, orderLines, deliverTo, invoiceTo, cup, cig, invoiceComments, deliveryNoteComments, shipmentPurpose, extraEmailAddresses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDepotOrderInput {\n");
    
    sb.append("    customerOrderId: ").append(toIndentedString(customerOrderId)).append("\n");
    sb.append("    orderLines: ").append(toIndentedString(orderLines)).append("\n");
    sb.append("    deliverTo: ").append(toIndentedString(deliverTo)).append("\n");
    sb.append("    invoiceTo: ").append(toIndentedString(invoiceTo)).append("\n");
    sb.append("    cup: ").append(toIndentedString(cup)).append("\n");
    sb.append("    cig: ").append(toIndentedString(cig)).append("\n");
    sb.append("    invoiceComments: ").append(toIndentedString(invoiceComments)).append("\n");
    sb.append("    deliveryNoteComments: ").append(toIndentedString(deliveryNoteComments)).append("\n");
    sb.append("    shipmentPurpose: ").append(toIndentedString(shipmentPurpose)).append("\n");
    sb.append("    extraEmailAddresses: ").append(toIndentedString(extraEmailAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

