/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CustomerDepotProductDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class CustomerDepotProductDto {
  @SerializedName("depotId")
  private String depotId = null;

  @SerializedName("productCode")
  private String productCode = null;

  @SerializedName("customerProductCode")
  private String customerProductCode = null;

  @SerializedName("esprinetProductCode")
  private String esprinetProductCode = null;

  @SerializedName("configuration")
  private String _configuration = null;

  @SerializedName("availability")
  private Integer availability = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("warehouseValue")
  private Double warehouseValue = null;

  public CustomerDepotProductDto depotId(String depotId) {
    this.depotId = depotId;
    return this;
  }

   /**
   * Get depotId
   * @return depotId
  **/
  @ApiModelProperty(value = "")
  public String getDepotId() {
    return depotId;
  }

  public void setDepotId(String depotId) {
    this.depotId = depotId;
  }

  public CustomerDepotProductDto productCode(String productCode) {
    this.productCode = productCode;
    return this;
  }

   /**
   * Get productCode
   * @return productCode
  **/
  @ApiModelProperty(value = "")
  public String getProductCode() {
    return productCode;
  }

  public void setProductCode(String productCode) {
    this.productCode = productCode;
  }

  public CustomerDepotProductDto customerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
    return this;
  }

   /**
   * Get customerProductCode
   * @return customerProductCode
  **/
  @ApiModelProperty(value = "")
  public String getCustomerProductCode() {
    return customerProductCode;
  }

  public void setCustomerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
  }

  public CustomerDepotProductDto esprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
    return this;
  }

   /**
   * Get esprinetProductCode
   * @return esprinetProductCode
  **/
  @ApiModelProperty(value = "")
  public String getEsprinetProductCode() {
    return esprinetProductCode;
  }

  public void setEsprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
  }

  public CustomerDepotProductDto _configuration(String _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @ApiModelProperty(value = "")
  public String getConfiguration() {
    return _configuration;
  }

  public void setConfiguration(String _configuration) {
    this._configuration = _configuration;
  }

  public CustomerDepotProductDto availability(Integer availability) {
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getAvailability() {
    return availability;
  }

  public void setAvailability(Integer availability) {
    this.availability = availability;
  }

  public CustomerDepotProductDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomerDepotProductDto warehouseValue(Double warehouseValue) {
    this.warehouseValue = warehouseValue;
    return this;
  }

   /**
   * Get warehouseValue
   * @return warehouseValue
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getWarehouseValue() {
    return warehouseValue;
  }

  public void setWarehouseValue(Double warehouseValue) {
    this.warehouseValue = warehouseValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDepotProductDto customerDepotProductDto = (CustomerDepotProductDto) o;
    return Objects.equals(this.depotId, customerDepotProductDto.depotId) &&
        Objects.equals(this.productCode, customerDepotProductDto.productCode) &&
        Objects.equals(this.customerProductCode, customerDepotProductDto.customerProductCode) &&
        Objects.equals(this.esprinetProductCode, customerDepotProductDto.esprinetProductCode) &&
        Objects.equals(this._configuration, customerDepotProductDto._configuration) &&
        Objects.equals(this.availability, customerDepotProductDto.availability) &&
        Objects.equals(this.description, customerDepotProductDto.description) &&
        Objects.equals(this.warehouseValue, customerDepotProductDto.warehouseValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(depotId, productCode, customerProductCode, esprinetProductCode, _configuration, availability, description, warehouseValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDepotProductDto {\n");
    
    sb.append("    depotId: ").append(toIndentedString(depotId)).append("\n");
    sb.append("    productCode: ").append(toIndentedString(productCode)).append("\n");
    sb.append("    customerProductCode: ").append(toIndentedString(customerProductCode)).append("\n");
    sb.append("    esprinetProductCode: ").append(toIndentedString(esprinetProductCode)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    warehouseValue: ").append(toIndentedString(warehouseValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

