/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.CustomerDepotOrderDto;
import org.lamemind.esprinetclient.model.OperationResult;
import org.lamemind.esprinetclient.model.PagingInfo;

/**
 * CustomerDepotOrdersOutput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class CustomerDepotOrdersOutput {
  @SerializedName("customerDepotOrders")
  private List<CustomerDepotOrderDto> customerDepotOrders = null;

  @SerializedName("pagingInfo")
  private PagingInfo pagingInfo = null;

  @SerializedName("operationResult")
  private OperationResult operationResult = null;

  public CustomerDepotOrdersOutput customerDepotOrders(List<CustomerDepotOrderDto> customerDepotOrders) {
    this.customerDepotOrders = customerDepotOrders;
    return this;
  }

  public CustomerDepotOrdersOutput addCustomerDepotOrdersItem(CustomerDepotOrderDto customerDepotOrdersItem) {
    if (this.customerDepotOrders == null) {
      this.customerDepotOrders = new ArrayList<CustomerDepotOrderDto>();
    }
    this.customerDepotOrders.add(customerDepotOrdersItem);
    return this;
  }

   /**
   * Contains all the available informations about the requested orders.
   * @return customerDepotOrders
  **/
  @ApiModelProperty(value = "Contains all the available informations about the requested orders.")
  public List<CustomerDepotOrderDto> getCustomerDepotOrders() {
    return customerDepotOrders;
  }

  public void setCustomerDepotOrders(List<CustomerDepotOrderDto> customerDepotOrders) {
    this.customerDepotOrders = customerDepotOrders;
  }

  public CustomerDepotOrdersOutput pagingInfo(PagingInfo pagingInfo) {
    this.pagingInfo = pagingInfo;
    return this;
  }

   /**
   * Gets or sets the paging information.
   * @return pagingInfo
  **/
  @ApiModelProperty(value = "Gets or sets the paging information.")
  public PagingInfo getPagingInfo() {
    return pagingInfo;
  }

  public void setPagingInfo(PagingInfo pagingInfo) {
    this.pagingInfo = pagingInfo;
  }

  public CustomerDepotOrdersOutput operationResult(OperationResult operationResult) {
    this.operationResult = operationResult;
    return this;
  }

   /**
   * Contains information about the result of this service call.
   * @return operationResult
  **/
  @ApiModelProperty(required = true, value = "Contains information about the result of this service call.")
  public OperationResult getOperationResult() {
    return operationResult;
  }

  public void setOperationResult(OperationResult operationResult) {
    this.operationResult = operationResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerDepotOrdersOutput customerDepotOrdersOutput = (CustomerDepotOrdersOutput) o;
    return Objects.equals(this.customerDepotOrders, customerDepotOrdersOutput.customerDepotOrders) &&
        Objects.equals(this.pagingInfo, customerDepotOrdersOutput.pagingInfo) &&
        Objects.equals(this.operationResult, customerDepotOrdersOutput.operationResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerDepotOrders, pagingInfo, operationResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerDepotOrdersOutput {\n");
    
    sb.append("    customerDepotOrders: ").append(toIndentedString(customerDepotOrders)).append("\n");
    sb.append("    pagingInfo: ").append(toIndentedString(pagingInfo)).append("\n");
    sb.append("    operationResult: ").append(toIndentedString(operationResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

