/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.OperationDetailResultDto;
import org.threeten.bp.OffsetDateTime;

/**
 * OperationResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class OperationResult {
  @SerializedName("beginDate")
  private OffsetDateTime beginDate = null;

  @SerializedName("endDate")
  private OffsetDateTime endDate = null;

  @SerializedName("esprinetTransactionId")
  private String esprinetTransactionId = null;

  @SerializedName("consumerTransactionId")
  private String consumerTransactionId = null;

  @SerializedName("resultDetails")
  private List<OperationDetailResultDto> resultDetails = null;

  public OperationResult beginDate(OffsetDateTime beginDate) {
    this.beginDate = beginDate;
    return this;
  }

   /**
   * Date and time of when the transaction started (DD/MM/YYYY HH:MM:SS).
   * @return beginDate
  **/
  @ApiModelProperty(required = true, value = "Date and time of when the transaction started (DD/MM/YYYY HH:MM:SS).")
  public OffsetDateTime getBeginDate() {
    return beginDate;
  }

  public void setBeginDate(OffsetDateTime beginDate) {
    this.beginDate = beginDate;
  }

  public OperationResult endDate(OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Date and time of when the transaction completed (DD/MM/YYYY HH:MM:SS).
   * @return endDate
  **/
  @ApiModelProperty(required = true, value = "Date and time of when the transaction completed (DD/MM/YYYY HH:MM:SS).")
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  public OperationResult esprinetTransactionId(String esprinetTransactionId) {
    this.esprinetTransactionId = esprinetTransactionId;
    return this;
  }

   /**
   * Unique transaction id generated by the Esprinet systems.
   * @return esprinetTransactionId
  **/
  @ApiModelProperty(value = "Unique transaction id generated by the Esprinet systems.")
  public String getEsprinetTransactionId() {
    return esprinetTransactionId;
  }

  public void setEsprinetTransactionId(String esprinetTransactionId) {
    this.esprinetTransactionId = esprinetTransactionId;
  }

  public OperationResult consumerTransactionId(String consumerTransactionId) {
    this.consumerTransactionId = consumerTransactionId;
    return this;
  }

   /**
   * Unique transaction id generated given by the customer
   * @return consumerTransactionId
  **/
  @ApiModelProperty(value = "Unique transaction id generated given by the customer")
  public String getConsumerTransactionId() {
    return consumerTransactionId;
  }

  public void setConsumerTransactionId(String consumerTransactionId) {
    this.consumerTransactionId = consumerTransactionId;
  }

  public OperationResult resultDetails(List<OperationDetailResultDto> resultDetails) {
    this.resultDetails = resultDetails;
    return this;
  }

  public OperationResult addResultDetailsItem(OperationDetailResultDto resultDetailsItem) {
    if (this.resultDetails == null) {
      this.resultDetails = new ArrayList<OperationDetailResultDto>();
    }
    this.resultDetails.add(resultDetailsItem);
    return this;
  }

   /**
   * If the request is made of multiple actions which can fail independently this object may contain all the independent result items.
   * @return resultDetails
  **/
  @ApiModelProperty(value = "If the request is made of multiple actions which can fail independently this object may contain all the independent result items.")
  public List<OperationDetailResultDto> getResultDetails() {
    return resultDetails;
  }

  public void setResultDetails(List<OperationDetailResultDto> resultDetails) {
    this.resultDetails = resultDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationResult operationResult = (OperationResult) o;
    return Objects.equals(this.beginDate, operationResult.beginDate) &&
        Objects.equals(this.endDate, operationResult.endDate) &&
        Objects.equals(this.esprinetTransactionId, operationResult.esprinetTransactionId) &&
        Objects.equals(this.consumerTransactionId, operationResult.consumerTransactionId) &&
        Objects.equals(this.resultDetails, operationResult.resultDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beginDate, endDate, esprinetTransactionId, consumerTransactionId, resultDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationResult {\n");
    
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    esprinetTransactionId: ").append(toIndentedString(esprinetTransactionId)).append("\n");
    sb.append("    consumerTransactionId: ").append(toIndentedString(consumerTransactionId)).append("\n");
    sb.append("    resultDetails: ").append(toIndentedString(resultDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

