/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.Address;
import org.lamemind.esprinetclient.model.OrderLineDto;
import org.threeten.bp.OffsetDateTime;

/**
 * OrderDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class OrderDto {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("orderDate")
  private OffsetDateTime orderDate = null;

  @SerializedName("esprinetOrderId")
  private String esprinetOrderId = null;

  @SerializedName("orderStatusId")
  private String orderStatusId = null;

  @SerializedName("orderStatusDescription")
  private String orderStatusDescription = null;

  @SerializedName("customerOrderId")
  private String customerOrderId = null;

  @SerializedName("customerComments")
  private String customerComments = null;

  @SerializedName("deliverTo")
  private Address deliverTo = null;

  @SerializedName("isCustomerDeliveryNote")
  private Boolean isCustomerDeliveryNote = null;

  @SerializedName("lockedOnCreation")
  private Boolean lockedOnCreation = null;

  @SerializedName("orderLines")
  private List<OrderLineDto> orderLines = null;

  @SerializedName("requestedDeliveryDate")
  private OffsetDateTime requestedDeliveryDate = null;

  @SerializedName("currency")
  private String currency = null;

  @SerializedName("orderType")
  private String orderType = null;

  @SerializedName("isUpdatable")
  private Boolean isUpdatable = null;

  @SerializedName("isFreightForwarding")
  private Boolean isFreightForwarding = null;

  public OrderDto id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Esprinet-generated order number.
   * @return id
  **/
  @ApiModelProperty(value = "Esprinet-generated order number.")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public OrderDto orderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
    return this;
  }

   /**
   * Date of when the order has been created.
   * @return orderDate
  **/
  @ApiModelProperty(required = true, value = "Date of when the order has been created.")
  public OffsetDateTime getOrderDate() {
    return orderDate;
  }

  public void setOrderDate(OffsetDateTime orderDate) {
    this.orderDate = orderDate;
  }

  public OrderDto esprinetOrderId(String esprinetOrderId) {
    this.esprinetOrderId = esprinetOrderId;
    return this;
  }

   /**
   * Esprinet-generated order id.
   * @return esprinetOrderId
  **/
  @ApiModelProperty(value = "Esprinet-generated order id.")
  public String getEsprinetOrderId() {
    return esprinetOrderId;
  }

  public void setEsprinetOrderId(String esprinetOrderId) {
    this.esprinetOrderId = esprinetOrderId;
  }

  public OrderDto orderStatusId(String orderStatusId) {
    this.orderStatusId = orderStatusId;
    return this;
  }

   /**
   * Esprinet order status id.
   * @return orderStatusId
  **/
  @ApiModelProperty(value = "Esprinet order status id.")
  public String getOrderStatusId() {
    return orderStatusId;
  }

  public void setOrderStatusId(String orderStatusId) {
    this.orderStatusId = orderStatusId;
  }

  public OrderDto orderStatusDescription(String orderStatusDescription) {
    this.orderStatusDescription = orderStatusDescription;
    return this;
  }

   /**
   * Esprinet order status description.
   * @return orderStatusDescription
  **/
  @ApiModelProperty(value = "Esprinet order status description.")
  public String getOrderStatusDescription() {
    return orderStatusDescription;
  }

  public void setOrderStatusDescription(String orderStatusDescription) {
    this.orderStatusDescription = orderStatusDescription;
  }

  public OrderDto customerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
    return this;
  }

   /**
   * Customer-generated order id.
   * @return customerOrderId
  **/
  @ApiModelProperty(value = "Customer-generated order id.")
  public String getCustomerOrderId() {
    return customerOrderId;
  }

  public void setCustomerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
  }

  public OrderDto customerComments(String customerComments) {
    this.customerComments = customerComments;
    return this;
  }

   /**
   * Customer notes related to the order.
   * @return customerComments
  **/
  @ApiModelProperty(value = "Customer notes related to the order.")
  public String getCustomerComments() {
    return customerComments;
  }

  public void setCustomerComments(String customerComments) {
    this.customerComments = customerComments;
  }

  public OrderDto deliverTo(Address deliverTo) {
    this.deliverTo = deliverTo;
    return this;
  }

   /**
   * The address where the order items should be delivered to.
   * @return deliverTo
  **/
  @ApiModelProperty(value = "The address where the order items should be delivered to.")
  public Address getDeliverTo() {
    return deliverTo;
  }

  public void setDeliverTo(Address deliverTo) {
    this.deliverTo = deliverTo;
  }

  public OrderDto isCustomerDeliveryNote(Boolean isCustomerDeliveryNote) {
    this.isCustomerDeliveryNote = isCustomerDeliveryNote;
    return this;
  }

   /**
   * This field controls whether the shipping to the address specified within the order is done as appearing to come from Esprinet (when false) or from the customer who has placed the order (when true). This usually involves putting the customer logos and details in the delivery note which accompanies every shipping. This feature can be used by a retailer who is placing an order for one of its customers and does want the shipping to appear to come from him.
   * @return isCustomerDeliveryNote
  **/
  @ApiModelProperty(required = true, value = "This field controls whether the shipping to the address specified within the order is done as appearing to come from Esprinet (when false) or from the customer who has placed the order (when true). This usually involves putting the customer logos and details in the delivery note which accompanies every shipping. This feature can be used by a retailer who is placing an order for one of its customers and does want the shipping to appear to come from him.")
  public Boolean isIsCustomerDeliveryNote() {
    return isCustomerDeliveryNote;
  }

  public void setIsCustomerDeliveryNote(Boolean isCustomerDeliveryNote) {
    this.isCustomerDeliveryNote = isCustomerDeliveryNote;
  }

  public OrderDto lockedOnCreation(Boolean lockedOnCreation) {
    this.lockedOnCreation = lockedOnCreation;
    return this;
  }

   /**
   * This field controls whether the order is created as \&quot;locked\&quot; or not. When an order is created as \&quot;locked\&quot; the products it contains are \&quot;reserved\&quot; by the Esprinet systems (for only a short amount of time) but any further processing is \&quot;freezed\&quot; until the order is \&quot;unlocked\&quot; through a proper invocation of the ModifyOrder method. Restrictions on availability of this feature may apply, depending on contract agreement with Esprinet.
   * @return lockedOnCreation
  **/
  @ApiModelProperty(required = true, value = "This field controls whether the order is created as \"locked\" or not. When an order is created as \"locked\" the products it contains are \"reserved\" by the Esprinet systems (for only a short amount of time) but any further processing is \"freezed\" until the order is \"unlocked\" through a proper invocation of the ModifyOrder method. Restrictions on availability of this feature may apply, depending on contract agreement with Esprinet.")
  public Boolean isLockedOnCreation() {
    return lockedOnCreation;
  }

  public void setLockedOnCreation(Boolean lockedOnCreation) {
    this.lockedOnCreation = lockedOnCreation;
  }

  public OrderDto orderLines(List<OrderLineDto> orderLines) {
    this.orderLines = orderLines;
    return this;
  }

  public OrderDto addOrderLinesItem(OrderLineDto orderLinesItem) {
    if (this.orderLines == null) {
      this.orderLines = new ArrayList<OrderLineDto>();
    }
    this.orderLines.add(orderLinesItem);
    return this;
  }

   /**
   * Collection of lines (details) of the order.
   * @return orderLines
  **/
  @ApiModelProperty(value = "Collection of lines (details) of the order.")
  public List<OrderLineDto> getOrderLines() {
    return orderLines;
  }

  public void setOrderLines(List<OrderLineDto> orderLines) {
    this.orderLines = orderLines;
  }

  public OrderDto requestedDeliveryDate(OffsetDateTime requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
    return this;
  }

   /**
   * Date of when the order invoice has been delivered.
   * @return requestedDeliveryDate
  **/
  @ApiModelProperty(value = "Date of when the order invoice has been delivered.")
  public OffsetDateTime getRequestedDeliveryDate() {
    return requestedDeliveryDate;
  }

  public void setRequestedDeliveryDate(OffsetDateTime requestedDeliveryDate) {
    this.requestedDeliveryDate = requestedDeliveryDate;
  }

  public OrderDto currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * The order currency
   * @return currency
  **/
  @ApiModelProperty(value = "The order currency")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public OrderDto orderType(String orderType) {
    this.orderType = orderType;
    return this;
  }

   /**
   * the order Type
   * @return orderType
  **/
  @ApiModelProperty(value = "the order Type")
  public String getOrderType() {
    return orderType;
  }

  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  public OrderDto isUpdatable(Boolean isUpdatable) {
    this.isUpdatable = isUpdatable;
    return this;
  }

   /**
   * Indicate if the order can be updated
   * @return isUpdatable
  **/
  @ApiModelProperty(required = true, value = "Indicate if the order can be updated")
  public Boolean isIsUpdatable() {
    return isUpdatable;
  }

  public void setIsUpdatable(Boolean isUpdatable) {
    this.isUpdatable = isUpdatable;
  }

  public OrderDto isFreightForwarding(Boolean isFreightForwarding) {
    this.isFreightForwarding = isFreightForwarding;
    return this;
  }

   /**
   * the IsFreightForwarding field
   * @return isFreightForwarding
  **/
  @ApiModelProperty(required = true, value = "the IsFreightForwarding field")
  public Boolean isIsFreightForwarding() {
    return isFreightForwarding;
  }

  public void setIsFreightForwarding(Boolean isFreightForwarding) {
    this.isFreightForwarding = isFreightForwarding;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDto orderDto = (OrderDto) o;
    return Objects.equals(this.id, orderDto.id) &&
        Objects.equals(this.orderDate, orderDto.orderDate) &&
        Objects.equals(this.esprinetOrderId, orderDto.esprinetOrderId) &&
        Objects.equals(this.orderStatusId, orderDto.orderStatusId) &&
        Objects.equals(this.orderStatusDescription, orderDto.orderStatusDescription) &&
        Objects.equals(this.customerOrderId, orderDto.customerOrderId) &&
        Objects.equals(this.customerComments, orderDto.customerComments) &&
        Objects.equals(this.deliverTo, orderDto.deliverTo) &&
        Objects.equals(this.isCustomerDeliveryNote, orderDto.isCustomerDeliveryNote) &&
        Objects.equals(this.lockedOnCreation, orderDto.lockedOnCreation) &&
        Objects.equals(this.orderLines, orderDto.orderLines) &&
        Objects.equals(this.requestedDeliveryDate, orderDto.requestedDeliveryDate) &&
        Objects.equals(this.currency, orderDto.currency) &&
        Objects.equals(this.orderType, orderDto.orderType) &&
        Objects.equals(this.isUpdatable, orderDto.isUpdatable) &&
        Objects.equals(this.isFreightForwarding, orderDto.isFreightForwarding);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, orderDate, esprinetOrderId, orderStatusId, orderStatusDescription, customerOrderId, customerComments, deliverTo, isCustomerDeliveryNote, lockedOnCreation, orderLines, requestedDeliveryDate, currency, orderType, isUpdatable, isFreightForwarding);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    orderDate: ").append(toIndentedString(orderDate)).append("\n");
    sb.append("    esprinetOrderId: ").append(toIndentedString(esprinetOrderId)).append("\n");
    sb.append("    orderStatusId: ").append(toIndentedString(orderStatusId)).append("\n");
    sb.append("    orderStatusDescription: ").append(toIndentedString(orderStatusDescription)).append("\n");
    sb.append("    customerOrderId: ").append(toIndentedString(customerOrderId)).append("\n");
    sb.append("    customerComments: ").append(toIndentedString(customerComments)).append("\n");
    sb.append("    deliverTo: ").append(toIndentedString(deliverTo)).append("\n");
    sb.append("    isCustomerDeliveryNote: ").append(toIndentedString(isCustomerDeliveryNote)).append("\n");
    sb.append("    lockedOnCreation: ").append(toIndentedString(lockedOnCreation)).append("\n");
    sb.append("    orderLines: ").append(toIndentedString(orderLines)).append("\n");
    sb.append("    requestedDeliveryDate: ").append(toIndentedString(requestedDeliveryDate)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    orderType: ").append(toIndentedString(orderType)).append("\n");
    sb.append("    isUpdatable: ").append(toIndentedString(isUpdatable)).append("\n");
    sb.append("    isFreightForwarding: ").append(toIndentedString(isFreightForwarding)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

