/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.QuotationProductInputDto;

/**
 * QuotationsInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class QuotationsInput {
  @SerializedName("customerQuotationReference")
  private String customerQuotationReference = null;

  @SerializedName("products")
  private List<QuotationProductInputDto> products = new ArrayList<QuotationProductInputDto>();

  public QuotationsInput customerQuotationReference(String customerQuotationReference) {
    this.customerQuotationReference = customerQuotationReference;
    return this;
  }

   /**
   * Get customerQuotationReference
   * @return customerQuotationReference
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCustomerQuotationReference() {
    return customerQuotationReference;
  }

  public void setCustomerQuotationReference(String customerQuotationReference) {
    this.customerQuotationReference = customerQuotationReference;
  }

  public QuotationsInput products(List<QuotationProductInputDto> products) {
    this.products = products;
    return this;
  }

  public QuotationsInput addProductsItem(QuotationProductInputDto productsItem) {
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @ApiModelProperty(required = true, value = "")
  public List<QuotationProductInputDto> getProducts() {
    return products;
  }

  public void setProducts(List<QuotationProductInputDto> products) {
    this.products = products;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotationsInput quotationsInput = (QuotationsInput) o;
    return Objects.equals(this.customerQuotationReference, quotationsInput.customerQuotationReference) &&
        Objects.equals(this.products, quotationsInput.products);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerQuotationReference, products);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotationsInput {\n");
    
    sb.append("    customerQuotationReference: ").append(toIndentedString(customerQuotationReference)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

