/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.lamemind.esprinetclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.lamemind.esprinetclient.model.DeliveryNoteDto;
import org.lamemind.esprinetclient.model.OperationResult;
import org.lamemind.esprinetclient.model.PagingInfo;

/**
 * SearchDeliveryNotesOutput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T15:47:59.649+01:00")
public class SearchDeliveryNotesOutput {
  @SerializedName("deliveryNotes")
  private List<DeliveryNoteDto> deliveryNotes = null;

  @SerializedName("pagingInfo")
  private PagingInfo pagingInfo = null;

  @SerializedName("operationResult")
  private OperationResult operationResult = null;

  public SearchDeliveryNotesOutput deliveryNotes(List<DeliveryNoteDto> deliveryNotes) {
    this.deliveryNotes = deliveryNotes;
    return this;
  }

  public SearchDeliveryNotesOutput addDeliveryNotesItem(DeliveryNoteDto deliveryNotesItem) {
    if (this.deliveryNotes == null) {
      this.deliveryNotes = new ArrayList<DeliveryNoteDto>();
    }
    this.deliveryNotes.add(deliveryNotesItem);
    return this;
  }

   /**
   * The list of found delivery notes satisfying the specified search criteria.
   * @return deliveryNotes
  **/
  @ApiModelProperty(value = "The list of found delivery notes satisfying the specified search criteria.")
  public List<DeliveryNoteDto> getDeliveryNotes() {
    return deliveryNotes;
  }

  public void setDeliveryNotes(List<DeliveryNoteDto> deliveryNotes) {
    this.deliveryNotes = deliveryNotes;
  }

  public SearchDeliveryNotesOutput pagingInfo(PagingInfo pagingInfo) {
    this.pagingInfo = pagingInfo;
    return this;
  }

   /**
   * Gets the paging information.
   * @return pagingInfo
  **/
  @ApiModelProperty(value = "Gets the paging information.")
  public PagingInfo getPagingInfo() {
    return pagingInfo;
  }

  public void setPagingInfo(PagingInfo pagingInfo) {
    this.pagingInfo = pagingInfo;
  }

  public SearchDeliveryNotesOutput operationResult(OperationResult operationResult) {
    this.operationResult = operationResult;
    return this;
  }

   /**
   * Contains information about the result of this service call.
   * @return operationResult
  **/
  @ApiModelProperty(required = true, value = "Contains information about the result of this service call.")
  public OperationResult getOperationResult() {
    return operationResult;
  }

  public void setOperationResult(OperationResult operationResult) {
    this.operationResult = operationResult;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchDeliveryNotesOutput searchDeliveryNotesOutput = (SearchDeliveryNotesOutput) o;
    return Objects.equals(this.deliveryNotes, searchDeliveryNotesOutput.deliveryNotes) &&
        Objects.equals(this.pagingInfo, searchDeliveryNotesOutput.pagingInfo) &&
        Objects.equals(this.operationResult, searchDeliveryNotesOutput.operationResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryNotes, pagingInfo, operationResult);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchDeliveryNotesOutput {\n");
    
    sb.append("    deliveryNotes: ").append(toIndentedString(deliveryNotes)).append("\n");
    sb.append("    pagingInfo: ").append(toIndentedString(pagingInfo)).append("\n");
    sb.append("    operationResult: ").append(toIndentedString(operationResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

