/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CashAndCarriesProductAvailabilityByCodeDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class CashAndCarriesProductAvailabilityByCodeDto {
  @SerializedName("stock")
  private Integer stock = null;

  @SerializedName("cashAndCarryId")
  private String cashAndCarryId = null;

  @SerializedName("cashAndCarryName")
  private String cashAndCarryName = null;

  @SerializedName("esprinetProductCode")
  private String esprinetProductCode = null;

  @SerializedName("vendorProductCode")
  private String vendorProductCode = null;

  @SerializedName("customerProductCode")
  private String customerProductCode = null;

  @SerializedName("rotationClass")
  private String rotationClass = null;

  public CashAndCarriesProductAvailabilityByCodeDto stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * Get stock
   * @return stock
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStock() {
    return stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }

  public CashAndCarriesProductAvailabilityByCodeDto cashAndCarryId(String cashAndCarryId) {
    this.cashAndCarryId = cashAndCarryId;
    return this;
  }

   /**
   * Get cashAndCarryId
   * @return cashAndCarryId
  **/
  @ApiModelProperty(value = "")
  public String getCashAndCarryId() {
    return cashAndCarryId;
  }

  public void setCashAndCarryId(String cashAndCarryId) {
    this.cashAndCarryId = cashAndCarryId;
  }

  public CashAndCarriesProductAvailabilityByCodeDto cashAndCarryName(String cashAndCarryName) {
    this.cashAndCarryName = cashAndCarryName;
    return this;
  }

   /**
   * Get cashAndCarryName
   * @return cashAndCarryName
  **/
  @ApiModelProperty(value = "")
  public String getCashAndCarryName() {
    return cashAndCarryName;
  }

  public void setCashAndCarryName(String cashAndCarryName) {
    this.cashAndCarryName = cashAndCarryName;
  }

  public CashAndCarriesProductAvailabilityByCodeDto esprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
    return this;
  }

   /**
   * Get esprinetProductCode
   * @return esprinetProductCode
  **/
  @ApiModelProperty(value = "")
  public String getEsprinetProductCode() {
    return esprinetProductCode;
  }

  public void setEsprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
  }

  public CashAndCarriesProductAvailabilityByCodeDto vendorProductCode(String vendorProductCode) {
    this.vendorProductCode = vendorProductCode;
    return this;
  }

   /**
   * Get vendorProductCode
   * @return vendorProductCode
  **/
  @ApiModelProperty(value = "")
  public String getVendorProductCode() {
    return vendorProductCode;
  }

  public void setVendorProductCode(String vendorProductCode) {
    this.vendorProductCode = vendorProductCode;
  }

  public CashAndCarriesProductAvailabilityByCodeDto customerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
    return this;
  }

   /**
   * Get customerProductCode
   * @return customerProductCode
  **/
  @ApiModelProperty(value = "")
  public String getCustomerProductCode() {
    return customerProductCode;
  }

  public void setCustomerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
  }

  public CashAndCarriesProductAvailabilityByCodeDto rotationClass(String rotationClass) {
    this.rotationClass = rotationClass;
    return this;
  }

   /**
   * Get rotationClass
   * @return rotationClass
  **/
  @ApiModelProperty(value = "")
  public String getRotationClass() {
    return rotationClass;
  }

  public void setRotationClass(String rotationClass) {
    this.rotationClass = rotationClass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashAndCarriesProductAvailabilityByCodeDto cashAndCarriesProductAvailabilityByCodeDto = (CashAndCarriesProductAvailabilityByCodeDto) o;
    return Objects.equals(this.stock, cashAndCarriesProductAvailabilityByCodeDto.stock) &&
        Objects.equals(this.cashAndCarryId, cashAndCarriesProductAvailabilityByCodeDto.cashAndCarryId) &&
        Objects.equals(this.cashAndCarryName, cashAndCarriesProductAvailabilityByCodeDto.cashAndCarryName) &&
        Objects.equals(this.esprinetProductCode, cashAndCarriesProductAvailabilityByCodeDto.esprinetProductCode) &&
        Objects.equals(this.vendorProductCode, cashAndCarriesProductAvailabilityByCodeDto.vendorProductCode) &&
        Objects.equals(this.customerProductCode, cashAndCarriesProductAvailabilityByCodeDto.customerProductCode) &&
        Objects.equals(this.rotationClass, cashAndCarriesProductAvailabilityByCodeDto.rotationClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stock, cashAndCarryId, cashAndCarryName, esprinetProductCode, vendorProductCode, customerProductCode, rotationClass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashAndCarriesProductAvailabilityByCodeDto {\n");
    
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    cashAndCarryId: ").append(toIndentedString(cashAndCarryId)).append("\n");
    sb.append("    cashAndCarryName: ").append(toIndentedString(cashAndCarryName)).append("\n");
    sb.append("    esprinetProductCode: ").append(toIndentedString(esprinetProductCode)).append("\n");
    sb.append("    vendorProductCode: ").append(toIndentedString(vendorProductCode)).append("\n");
    sb.append("    customerProductCode: ").append(toIndentedString(customerProductCode)).append("\n");
    sb.append("    rotationClass: ").append(toIndentedString(rotationClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

