/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DeliveryNoteLineDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class DeliveryNoteLineDto {
  @SerializedName("esprinetLineNumber")
  private Integer esprinetLineNumber = null;

  @SerializedName("esprinetProductCode")
  private String esprinetProductCode = null;

  @SerializedName("customerProductCode")
  private String customerProductCode = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("vat")
  private Double vat = null;

  @SerializedName("taxes")
  private Double taxes = null;

  @SerializedName("serialNumbers")
  private List<String> serialNumbers = null;

  public DeliveryNoteLineDto esprinetLineNumber(Integer esprinetLineNumber) {
    this.esprinetLineNumber = esprinetLineNumber;
    return this;
  }

   /**
   * Get esprinetLineNumber
   * @return esprinetLineNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEsprinetLineNumber() {
    return esprinetLineNumber;
  }

  public void setEsprinetLineNumber(Integer esprinetLineNumber) {
    this.esprinetLineNumber = esprinetLineNumber;
  }

  public DeliveryNoteLineDto esprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
    return this;
  }

   /**
   * Esprinet product code.
   * @return esprinetProductCode
  **/
  @ApiModelProperty(value = "Esprinet product code.")
  public String getEsprinetProductCode() {
    return esprinetProductCode;
  }

  public void setEsprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
  }

  public DeliveryNoteLineDto customerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
    return this;
  }

   /**
   * Customer product code (if available).
   * @return customerProductCode
  **/
  @ApiModelProperty(value = "Customer product code (if available).")
  public String getCustomerProductCode() {
    return customerProductCode;
  }

  public void setCustomerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
  }

  public DeliveryNoteLineDto quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Amount of ordered items.
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "Amount of ordered items.")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public DeliveryNoteLineDto price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Single item price. The final price including discounts is calculated at runtime by Esprinet systems when the order is confirmed.
   * @return price
  **/
  @ApiModelProperty(value = "Single item price. The final price including discounts is calculated at runtime by Esprinet systems when the order is confirmed.")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public DeliveryNoteLineDto vat(Double vat) {
    this.vat = vat;
    return this;
  }

   /**
   * Amount of Vat.
   * @return vat
  **/
  @ApiModelProperty(required = true, value = "Amount of Vat.")
  public Double getVat() {
    return vat;
  }

  public void setVat(Double vat) {
    this.vat = vat;
  }

  public DeliveryNoteLineDto taxes(Double taxes) {
    this.taxes = taxes;
    return this;
  }

   /**
   * Total amount of taxes
   * @return taxes
  **/
  @ApiModelProperty(required = true, value = "Total amount of taxes")
  public Double getTaxes() {
    return taxes;
  }

  public void setTaxes(Double taxes) {
    this.taxes = taxes;
  }

  public DeliveryNoteLineDto serialNumbers(List<String> serialNumbers) {
    this.serialNumbers = serialNumbers;
    return this;
  }

  public DeliveryNoteLineDto addSerialNumbersItem(String serialNumbersItem) {
    if (this.serialNumbers == null) {
      this.serialNumbers = new ArrayList<String>();
    }
    this.serialNumbers.add(serialNumbersItem);
    return this;
  }

   /**
   * Get serialNumbers
   * @return serialNumbers
  **/
  @ApiModelProperty(value = "")
  public List<String> getSerialNumbers() {
    return serialNumbers;
  }

  public void setSerialNumbers(List<String> serialNumbers) {
    this.serialNumbers = serialNumbers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryNoteLineDto deliveryNoteLineDto = (DeliveryNoteLineDto) o;
    return Objects.equals(this.esprinetLineNumber, deliveryNoteLineDto.esprinetLineNumber) &&
        Objects.equals(this.esprinetProductCode, deliveryNoteLineDto.esprinetProductCode) &&
        Objects.equals(this.customerProductCode, deliveryNoteLineDto.customerProductCode) &&
        Objects.equals(this.quantity, deliveryNoteLineDto.quantity) &&
        Objects.equals(this.price, deliveryNoteLineDto.price) &&
        Objects.equals(this.vat, deliveryNoteLineDto.vat) &&
        Objects.equals(this.taxes, deliveryNoteLineDto.taxes) &&
        Objects.equals(this.serialNumbers, deliveryNoteLineDto.serialNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(esprinetLineNumber, esprinetProductCode, customerProductCode, quantity, price, vat, taxes, serialNumbers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeliveryNoteLineDto {\n");
    
    sb.append("    esprinetLineNumber: ").append(toIndentedString(esprinetLineNumber)).append("\n");
    sb.append("    esprinetProductCode: ").append(toIndentedString(esprinetProductCode)).append("\n");
    sb.append("    customerProductCode: ").append(toIndentedString(customerProductCode)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    vat: ").append(toIndentedString(vat)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    serialNumbers: ").append(toIndentedString(serialNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

