/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ExpectedArrival
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class ExpectedArrival {
  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("expectedDate")
  private OffsetDateTime expectedDate = null;

  @SerializedName("forecastQuality")
  private Integer forecastQuality = null;

  public ExpectedArrival quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public ExpectedArrival expectedDate(OffsetDateTime expectedDate) {
    this.expectedDate = expectedDate;
    return this;
  }

   /**
   * Get expectedDate
   * @return expectedDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getExpectedDate() {
    return expectedDate;
  }

  public void setExpectedDate(OffsetDateTime expectedDate) {
    this.expectedDate = expectedDate;
  }

  public ExpectedArrival forecastQuality(Integer forecastQuality) {
    this.forecastQuality = forecastQuality;
    return this;
  }

   /**
   * Get forecastQuality
   * @return forecastQuality
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getForecastQuality() {
    return forecastQuality;
  }

  public void setForecastQuality(Integer forecastQuality) {
    this.forecastQuality = forecastQuality;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpectedArrival expectedArrival = (ExpectedArrival) o;
    return Objects.equals(this.quantity, expectedArrival.quantity) &&
        Objects.equals(this.expectedDate, expectedArrival.expectedDate) &&
        Objects.equals(this.forecastQuality, expectedArrival.forecastQuality);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quantity, expectedDate, forecastQuality);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpectedArrival {\n");
    
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    expectedDate: ").append(toIndentedString(expectedDate)).append("\n");
    sb.append("    forecastQuality: ").append(toIndentedString(forecastQuality)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

