/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModifyOrderLineInput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ModifyOrderInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class ModifyOrderInput {
  @SerializedName("customerOrderId")
  private String customerOrderId = null;

  @SerializedName("unlock")
  private Boolean unlock = null;

  @SerializedName("orderLines")
  private List<ModifyOrderLineInput> orderLines = null;

  public ModifyOrderInput customerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
    return this;
  }

   /**
   * The new Customer Order Id ({Esprinet.WebServices.Dtos.Order.OrderDto.CustomerOrderId}).  &lt;remarks&gt;Evaluate only when a customer order id update is required, leave blank or null otherwise.&lt;/remarks&gt;
   * @return customerOrderId
  **/
  @ApiModelProperty(value = "The new Customer Order Id ({Esprinet.WebServices.Dtos.Order.OrderDto.CustomerOrderId}).  <remarks>Evaluate only when a customer order id update is required, leave blank or null otherwise.</remarks>")
  public String getCustomerOrderId() {
    return customerOrderId;
  }

  public void setCustomerOrderId(String customerOrderId) {
    this.customerOrderId = customerOrderId;
  }

  public ModifyOrderInput unlock(Boolean unlock) {
    this.unlock = unlock;
    return this;
  }

   /**
   * Whether a contextual order unlock is requested.  &lt;remarks&gt;Evaluate to true only if a contextual unlock is required, false otherwise.&lt;/remarks&gt;
   * @return unlock
  **/
  @ApiModelProperty(required = true, value = "Whether a contextual order unlock is requested.  <remarks>Evaluate to true only if a contextual unlock is required, false otherwise.</remarks>")
  public Boolean isUnlock() {
    return unlock;
  }

  public void setUnlock(Boolean unlock) {
    this.unlock = unlock;
  }

  public ModifyOrderInput orderLines(List<ModifyOrderLineInput> orderLines) {
    this.orderLines = orderLines;
    return this;
  }

  public ModifyOrderInput addOrderLinesItem(ModifyOrderLineInput orderLinesItem) {
    if (this.orderLines == null) {
      this.orderLines = new ArrayList<ModifyOrderLineInput>();
    }
    this.orderLines.add(orderLinesItem);
    return this;
  }

   /**
   * Collection of optional line modifications.
   * @return orderLines
  **/
  @ApiModelProperty(value = "Collection of optional line modifications.")
  public List<ModifyOrderLineInput> getOrderLines() {
    return orderLines;
  }

  public void setOrderLines(List<ModifyOrderLineInput> orderLines) {
    this.orderLines = orderLines;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifyOrderInput modifyOrderInput = (ModifyOrderInput) o;
    return Objects.equals(this.customerOrderId, modifyOrderInput.customerOrderId) &&
        Objects.equals(this.unlock, modifyOrderInput.unlock) &&
        Objects.equals(this.orderLines, modifyOrderInput.orderLines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOrderId, unlock, orderLines);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyOrderInput {\n");
    
    sb.append("    customerOrderId: ").append(toIndentedString(customerOrderId)).append("\n");
    sb.append("    unlock: ").append(toIndentedString(unlock)).append("\n");
    sb.append("    orderLines: ").append(toIndentedString(orderLines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

