/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExpectedArrival;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ProductAvailabilityByCodeDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class ProductAvailabilityByCodeDto {
  @SerializedName("expectedArrivals")
  private List<ExpectedArrival> expectedArrivals = null;

  @SerializedName("stock")
  private Integer stock = null;

  @SerializedName("esprinetProductCode")
  private String esprinetProductCode = null;

  @SerializedName("vendorProductCode")
  private String vendorProductCode = null;

  @SerializedName("customerProductCode")
  private String customerProductCode = null;

  @SerializedName("rotationClass")
  private String rotationClass = null;

  public ProductAvailabilityByCodeDto expectedArrivals(List<ExpectedArrival> expectedArrivals) {
    this.expectedArrivals = expectedArrivals;
    return this;
  }

  public ProductAvailabilityByCodeDto addExpectedArrivalsItem(ExpectedArrival expectedArrivalsItem) {
    if (this.expectedArrivals == null) {
      this.expectedArrivals = new ArrayList<ExpectedArrival>();
    }
    this.expectedArrivals.add(expectedArrivalsItem);
    return this;
  }

   /**
   * Get expectedArrivals
   * @return expectedArrivals
  **/
  @ApiModelProperty(value = "")
  public List<ExpectedArrival> getExpectedArrivals() {
    return expectedArrivals;
  }

  public void setExpectedArrivals(List<ExpectedArrival> expectedArrivals) {
    this.expectedArrivals = expectedArrivals;
  }

  public ProductAvailabilityByCodeDto stock(Integer stock) {
    this.stock = stock;
    return this;
  }

   /**
   * Get stock
   * @return stock
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStock() {
    return stock;
  }

  public void setStock(Integer stock) {
    this.stock = stock;
  }

  public ProductAvailabilityByCodeDto esprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
    return this;
  }

   /**
   * Get esprinetProductCode
   * @return esprinetProductCode
  **/
  @ApiModelProperty(value = "")
  public String getEsprinetProductCode() {
    return esprinetProductCode;
  }

  public void setEsprinetProductCode(String esprinetProductCode) {
    this.esprinetProductCode = esprinetProductCode;
  }

  public ProductAvailabilityByCodeDto vendorProductCode(String vendorProductCode) {
    this.vendorProductCode = vendorProductCode;
    return this;
  }

   /**
   * Get vendorProductCode
   * @return vendorProductCode
  **/
  @ApiModelProperty(value = "")
  public String getVendorProductCode() {
    return vendorProductCode;
  }

  public void setVendorProductCode(String vendorProductCode) {
    this.vendorProductCode = vendorProductCode;
  }

  public ProductAvailabilityByCodeDto customerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
    return this;
  }

   /**
   * Get customerProductCode
   * @return customerProductCode
  **/
  @ApiModelProperty(value = "")
  public String getCustomerProductCode() {
    return customerProductCode;
  }

  public void setCustomerProductCode(String customerProductCode) {
    this.customerProductCode = customerProductCode;
  }

  public ProductAvailabilityByCodeDto rotationClass(String rotationClass) {
    this.rotationClass = rotationClass;
    return this;
  }

   /**
   * Get rotationClass
   * @return rotationClass
  **/
  @ApiModelProperty(value = "")
  public String getRotationClass() {
    return rotationClass;
  }

  public void setRotationClass(String rotationClass) {
    this.rotationClass = rotationClass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAvailabilityByCodeDto productAvailabilityByCodeDto = (ProductAvailabilityByCodeDto) o;
    return Objects.equals(this.expectedArrivals, productAvailabilityByCodeDto.expectedArrivals) &&
        Objects.equals(this.stock, productAvailabilityByCodeDto.stock) &&
        Objects.equals(this.esprinetProductCode, productAvailabilityByCodeDto.esprinetProductCode) &&
        Objects.equals(this.vendorProductCode, productAvailabilityByCodeDto.vendorProductCode) &&
        Objects.equals(this.customerProductCode, productAvailabilityByCodeDto.customerProductCode) &&
        Objects.equals(this.rotationClass, productAvailabilityByCodeDto.rotationClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expectedArrivals, stock, esprinetProductCode, vendorProductCode, customerProductCode, rotationClass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAvailabilityByCodeDto {\n");
    
    sb.append("    expectedArrivals: ").append(toIndentedString(expectedArrivals)).append("\n");
    sb.append("    stock: ").append(toIndentedString(stock)).append("\n");
    sb.append("    esprinetProductCode: ").append(toIndentedString(esprinetProductCode)).append("\n");
    sb.append("    vendorProductCode: ").append(toIndentedString(vendorProductCode)).append("\n");
    sb.append("    customerProductCode: ").append(toIndentedString(customerProductCode)).append("\n");
    sb.append("    rotationClass: ").append(toIndentedString(rotationClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

