/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ShippingInfoDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-12-17T14:59:51.596+01:00")
public class ShippingInfoDto {
  @SerializedName("shipperCode")
  private String shipperCode = null;

  @SerializedName("shipperDescription")
  private String shipperDescription = null;

  @SerializedName("shippingStatusCode")
  private String shippingStatusCode = null;

  @SerializedName("shippingStatusDescription")
  private String shippingStatusDescription = null;

  @SerializedName("shippingStatusDate")
  private OffsetDateTime shippingStatusDate = null;

  @SerializedName("trackingNumber")
  private String trackingNumber = null;

  @SerializedName("wayBill")
  private String wayBill = null;

  @SerializedName("carrierTrackingLink")
  private String carrierTrackingLink = null;

  public ShippingInfoDto shipperCode(String shipperCode) {
    this.shipperCode = shipperCode;
    return this;
  }

   /**
   * Identifies the shipping entity.
   * @return shipperCode
  **/
  @ApiModelProperty(value = "Identifies the shipping entity.")
  public String getShipperCode() {
    return shipperCode;
  }

  public void setShipperCode(String shipperCode) {
    this.shipperCode = shipperCode;
  }

  public ShippingInfoDto shipperDescription(String shipperDescription) {
    this.shipperDescription = shipperDescription;
    return this;
  }

   /**
   * A description for the shipping entity.
   * @return shipperDescription
  **/
  @ApiModelProperty(value = "A description for the shipping entity.")
  public String getShipperDescription() {
    return shipperDescription;
  }

  public void setShipperDescription(String shipperDescription) {
    this.shipperDescription = shipperDescription;
  }

  public ShippingInfoDto shippingStatusCode(String shippingStatusCode) {
    this.shippingStatusCode = shippingStatusCode;
    return this;
  }

   /**
   * Identifies the shipping status for a specific order line.
   * @return shippingStatusCode
  **/
  @ApiModelProperty(value = "Identifies the shipping status for a specific order line.")
  public String getShippingStatusCode() {
    return shippingStatusCode;
  }

  public void setShippingStatusCode(String shippingStatusCode) {
    this.shippingStatusCode = shippingStatusCode;
  }

  public ShippingInfoDto shippingStatusDescription(String shippingStatusDescription) {
    this.shippingStatusDescription = shippingStatusDescription;
    return this;
  }

   /**
   * A description of the shipping status for a specific order line.
   * @return shippingStatusDescription
  **/
  @ApiModelProperty(value = "A description of the shipping status for a specific order line.")
  public String getShippingStatusDescription() {
    return shippingStatusDescription;
  }

  public void setShippingStatusDescription(String shippingStatusDescription) {
    this.shippingStatusDescription = shippingStatusDescription;
  }

  public ShippingInfoDto shippingStatusDate(OffsetDateTime shippingStatusDate) {
    this.shippingStatusDate = shippingStatusDate;
    return this;
  }

   /**
   * The date which the above ShippingStatus refers to.
   * @return shippingStatusDate
  **/
  @ApiModelProperty(value = "The date which the above ShippingStatus refers to.")
  public OffsetDateTime getShippingStatusDate() {
    return shippingStatusDate;
  }

  public void setShippingStatusDate(OffsetDateTime shippingStatusDate) {
    this.shippingStatusDate = shippingStatusDate;
  }

  public ShippingInfoDto trackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * A specific number that allows to track, on the shipper&#39;s systems, the location of the shipping package.
   * @return trackingNumber
  **/
  @ApiModelProperty(value = "A specific number that allows to track, on the shipper's systems, the location of the shipping package.")
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public ShippingInfoDto wayBill(String wayBill) {
    this.wayBill = wayBill;
    return this;
  }

   /**
   * The shipping way billing info.
   * @return wayBill
  **/
  @ApiModelProperty(value = "The shipping way billing info.")
  public String getWayBill() {
    return wayBill;
  }

  public void setWayBill(String wayBill) {
    this.wayBill = wayBill;
  }

  public ShippingInfoDto carrierTrackingLink(String carrierTrackingLink) {
    this.carrierTrackingLink = carrierTrackingLink;
    return this;
  }

   /**
   * a list of direct links on the carrier&#39;s tracking system.
   * @return carrierTrackingLink
  **/
  @ApiModelProperty(value = "a list of direct links on the carrier's tracking system.")
  public String getCarrierTrackingLink() {
    return carrierTrackingLink;
  }

  public void setCarrierTrackingLink(String carrierTrackingLink) {
    this.carrierTrackingLink = carrierTrackingLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingInfoDto shippingInfoDto = (ShippingInfoDto) o;
    return Objects.equals(this.shipperCode, shippingInfoDto.shipperCode) &&
        Objects.equals(this.shipperDescription, shippingInfoDto.shipperDescription) &&
        Objects.equals(this.shippingStatusCode, shippingInfoDto.shippingStatusCode) &&
        Objects.equals(this.shippingStatusDescription, shippingInfoDto.shippingStatusDescription) &&
        Objects.equals(this.shippingStatusDate, shippingInfoDto.shippingStatusDate) &&
        Objects.equals(this.trackingNumber, shippingInfoDto.trackingNumber) &&
        Objects.equals(this.wayBill, shippingInfoDto.wayBill) &&
        Objects.equals(this.carrierTrackingLink, shippingInfoDto.carrierTrackingLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipperCode, shipperDescription, shippingStatusCode, shippingStatusDescription, shippingStatusDate, trackingNumber, wayBill, carrierTrackingLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingInfoDto {\n");
    
    sb.append("    shipperCode: ").append(toIndentedString(shipperCode)).append("\n");
    sb.append("    shipperDescription: ").append(toIndentedString(shipperDescription)).append("\n");
    sb.append("    shippingStatusCode: ").append(toIndentedString(shippingStatusCode)).append("\n");
    sb.append("    shippingStatusDescription: ").append(toIndentedString(shippingStatusDescription)).append("\n");
    sb.append("    shippingStatusDate: ").append(toIndentedString(shippingStatusDate)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    wayBill: ").append(toIndentedString(wayBill)).append("\n");
    sb.append("    carrierTrackingLink: ").append(toIndentedString(carrierTrackingLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

