/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.GetOrderInfoOutput;
import io.swagger.client.model.InsertOrderInput;
import io.swagger.client.model.InsertOrderOutput;
import io.swagger.client.model.ModifyOrderInput;
import org.threeten.bp.OffsetDateTime;
import io.swagger.client.model.OrderTransactionIdOutput;
import io.swagger.client.model.OrderTransactionOutput;
import io.swagger.client.model.OrdersSummaryOutput;
import io.swagger.client.model.SearchOrdersOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    
    /**
     * Delete the order with the given id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderDeleteTest() throws ApiException {
        String id = null;
        String xConsumerTransactionId = null;
        OrderTransactionIdOutput response = api.orderDelete(id, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Get an Order by the Order Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderGetTest() throws ApiException {
        String id = null;
        String xConsumerTransactionId = null;
        GetOrderInfoOutput response = api.orderGet(id, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Delete the order line with the given order line id of the given order
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderLinesDeleteTest() throws ApiException {
        String orderId = null;
        Integer orderLineId = null;
        String xConsumerTransactionId = null;
        OrderTransactionIdOutput response = api.orderLinesDelete(orderId, orderLineId, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Unlock the order with the given id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderPatchTest() throws ApiException {
        String id = null;
        String xConsumerTransactionId = null;
        OrderTransactionIdOutput response = api.orderPatch(id, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Creates a new order containing the specified list of products into the Esprinet systems.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderPostTest() throws ApiException {
        InsertOrderInput insertOrderInput = null;
        String xConsumerTransactionId = null;
        InsertOrderOutput response = api.orderPost(insertOrderInput, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Modifies an already existing order into the Esprinet systems.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderPutTest() throws ApiException {
        String id = null;
        ModifyOrderInput modifyOrderInput = null;
        String xConsumerTransactionId = null;
        OrderTransactionIdOutput response = api.orderPut(id, modifyOrderInput, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Return the tracking transaction by the transaction id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void orderTransactionsGetByIdTest() throws ApiException {
        Integer id = null;
        String xConsumerTransactionId = null;
        OrderTransactionOutput response = api.orderTransactionsGetById(id, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Obtains a list of orders, already existing into the Esprinet systems, satisfying the specified search criterias.  The search period should not exceed 30 days
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ordersSearchGetTest() throws ApiException {
        String customerOrderId = null;
        OffsetDateTime fromDate = null;
        OffsetDateTime toDate = null;
        String filter = null;
        Integer currentPage = null;
        String xConsumerTransactionId = null;
        SearchOrdersOutput response = api.ordersSearchGet(customerOrderId, fromDate, toDate, filter, currentPage, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Obtains a summary of orders satisfying the specified search criterias.  The search period should not exceed 30 days
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void ordersSummaryGetTest() throws ApiException {
        OffsetDateTime fromDate = null;
        OffsetDateTime toDate = null;
        String xConsumerTransactionId = null;
        OrdersSummaryOutput response = api.ordersSummaryGet(fromDate, toDate, xConsumerTransactionId);

        // TODO: test validations
    }
    
}
