/*
 * Esprinet Customer Rest Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * Contact: dl-ws-integration@esprinet.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ProductAvailabilityByCodeOutput;
import io.swagger.client.model.ProductPricingByCodeOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Ignore
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    
    /**
     * Get a Product Availability Info by the Esprinet or Customer product code
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsAvailabilityGetTest() throws ApiException {
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        ProductAvailabilityByCodeOutput response = api.productsAvailabilityGet(esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
    /**
     * Get a Product Pricing Info by the Esprinet or Customer product code
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void productsPricingGetTest() throws ApiException {
        String esprinetProductCode = null;
        String customerProductCode = null;
        String xConsumerTransactionId = null;
        ProductPricingByCodeOutput response = api.productsPricingGet(esprinetProductCode, customerProductCode, xConsumerTransactionId);

        // TODO: test validations
    }
    
}
